### ISSUE TITLE
Poor Fingerprinting Due to PIDs

### ISSUE THREAD

**Issue by jeremyjh** [Tubitv/logger_sentry#6]
One of the best features of Sentry is its fingerprinting - with exceptions for example it uses the stack trace and exception to fingerprint the message so that doesn't hammer you with lots of instances of the same error. Unfortunately it seems this doesn't work so well with logger_sentry as exceptions get sent to Logger.error with the PID as part of the text message.

Do you have any strategy for dealing with this? I want to keep `Logger.ErrorHandler` enabled, but don't want it sending exceptions with PIDs to Sentry. If you don't have a better solution would you take a PR that optionally strips PIDs out of the beginning of the message?

This is a partial example of the kind of message I'm talking about: 

```
(ErlangError) Erlang error: "#PID<0.9201.0> running SmartErp.Web.Endpoint (cowboy_protocol) terminated\nServer: cal.smarterp.io:80 (h
```

**Comment by clanchun** [comment]
Currently, we don't have a universal solution to the problem, because the uncaught exception's error message threw by Erlang runtime varies a lot. For example, here your message has a `PID` info, but `node` info and others can also exist in other error messages. These messages are hard to classify, so we let the user to decide how to generate fingerprints according to the error message.

You can custom your fingerprints here: https://github.com/Tubitv/logger_sentry/blob/master/lib/sentry.ex#L215-L220, for example, in your case here, you can strip the PIDs and return the new whole message as a fingerprint or extract some keywords like `[SmartErp.Web.Endpoint]` as fingerprints.
